#ifndef KATZIP_CONFIG_DEFAULTS_H
#define KATZIP_CONFIG_DEFAULTS_H

static const char katzip_default_ini[] =
  "# Compression settings for katzip. Levels 1-6 use libdeflate on files up to\n"
  "# 64 MiB. Larger files use streaming zlib at the selected level (capped at 9).\n"
  "# Levels 7-9 use Turtledeflate; level 9 also tries ECT Zopfli.\n"
  "\n"
  "[libdeflate-1]\n"
  "level = 1\n"
  "\n"
  "[libdeflate-2]\n"
  "level = 2\n"
  "\n"
  "[libdeflate-3]\n"
  "level = 3\n"
  "\n"
  "[libdeflate-4]\n"
  "level = 5\n"
  "\n"
  "[libdeflate-5]\n"
  "level = 6\n"
  "\n"
  "[libdeflate-6]\n"
  "level = 8\n"
  "\n"
  "[turtledeflate-7]\n"
  "i_compression_level = 7\n"
  "i_maximum_block_size = 32768\n"
  "i_maximum_subblocks = 8\n"
  "i_max_block_splitter_iterations = 2\n"
  "i_max_internal_block_splitter_iterations = 4\n"
  "i_block_splitter_num_points = 7\n"
  "i_block_splitter_center_dist = 2\n"
  "i_block_splitter_min_range_for_points = 1024\n"
  "b_block_splitter_push_split = 0\n"
  "i_min_start_fp = -3\n"
  "i_max_start_fp = 1\n"
  "i_num_start_fp = 3\n"
  "i_verbose = 0\n"
  "\n"
  "[turtledeflate-8]\n"
  "i_compression_level = 8\n"
  "i_maximum_block_size = 32768\n"
  "i_maximum_subblocks = 16\n"
  "i_max_block_splitter_iterations = 4\n"
  "i_max_internal_block_splitter_iterations = 10\n"
  "i_block_splitter_num_points = 15\n"
  "i_block_splitter_center_dist = 4\n"
  "i_block_splitter_min_range_for_points = 1024\n"
  "b_block_splitter_push_split = 0\n"
  "i_min_start_fp = -4\n"
  "i_max_start_fp = 3\n"
  "i_num_start_fp = 6\n"
  "i_verbose = 0\n"
  "\n"
  "[turtledeflate-9]\n"
  "i_compression_level = 9\n"
  "i_maximum_block_size = 1000000\n"
  "i_maximum_subblocks = 512\n"
  "i_max_block_splitter_iterations = 30\n"
  "i_max_internal_block_splitter_iterations = 100\n"
  "i_block_splitter_num_points = 31\n"
  "i_block_splitter_center_dist = 8\n"
  "i_block_splitter_min_range_for_points = 1024\n"
  "b_block_splitter_push_split = 1\n"
  "i_min_start_fp = -6\n"
  "i_max_start_fp = 5\n"
  "i_num_start_fp = 16\n"
  "i_verbose = 0\n"
;

#endif
